-- NOTE: Temprailly disabled until I learn how to setup LSP natively on 0.12

-- vim.lsp.enable({
--     "gopls",
--     "lua_ls",
--     "vtsls"
-- })
--
--
-- vim.api.nvim_create_autocmd('LspAttach', {
--     callback = function(ev)
--         local client = vim.lsp.get_client_by_id(ev.data.client_id)
--         if client and client:supports_method(vim.lsp.protocol.Methods.textDocument_completion) then
--             vim.opt.completeopt = { 'menu', 'menuone', 'noinsert', 'fuzzy', 'popup' }
--             vim.lsp.completion.enable(true, client.id, ev.buf, { autotrigger = true })
--             vim.keymap.set('i', '<C-Space>', function()
--                 vim.lsp.completion.get()
--             end)
--         end
--
--         -- keymap
--         local opts = { buffer = ev.buf, silent = true }
--         vim.keymap.set("n", "gd", vim.lsp.buf.declaration, opts)                  -- go to declaration
--         vim.keymap.set("n", "gr", "<cmd>Telescope lsp_references<CR>", opts)      -- show definition, references
--         vim.keymap.set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, opts) -- see available code actions, in visual mode will apply to selection
--     end,
-- })

--
-- vim.diagnostic.config({
--     -- virtual_lines = true,
--     virtual_text = true,
--     underline = true,
--     update_in_insert = false,
--     severity_sort = true,
--     float = {
--         border = "rounded",
--         source = true,
--     },
--     signs = {
--         text = {
--             [vim.diagnostic.severity.ERROR] = "󰅚 ",
--             [vim.diagnostic.severity.WARN] = "󰀪 ",
--             [vim.diagnostic.severity.INFO] = "󰋽 ",
--             [vim.diagnostic.severity.HINT] = "󰌶 ",
--         },
--         numhl = {
--             [vim.diagnostic.severity.ERROR] = "ErrorMsg",
--             [vim.diagnostic.severity.WARN] = "WarningMsg",
--         },
--     },
-- })
