require("core.keymap")
require("core.options")
require("core.autocommands")
require("core.theme")
require("core.lsp-config")
require("plugins")
require("modules")
require("utils.logger"):register_commands()
