-- Open ChatGPT with clipboard content as prompt
-- vim.keymap.set("n", "<leader>cc", function()
-- 	local text = vim.fn.getreg("+")
-- 	if text == "" then
-- 		vim.notify("Clipboard is empty", vim.log.levels.WARN)
-- 		return
-- 	end
--
-- 	local encoded = text:gsub(" ", "+")
-- 	local url = "https://chatgpt.com/?temporary-chat=true&prompt=" .. encoded
--
-- 	-- Open URL depending on OS
-- 	local cmd
-- 	if vim.fn.has("mac") == 1 then
-- 		cmd = { "open", url }
-- 	elseif vim.fn.has("unix") == 1 then
-- 		cmd = { "xdg-open", url }
-- 	elseif vim.fn.has("win32") == 1 then
-- 		cmd = { "cmd.exe", "/c", "start", url }
-- 	else
-- 		vim.notify("Unsupported OS", vim.log.levels.ERROR)
-- 		return
-- 	end
--
-- 	vim.fn.jobstart(cmd, { detach = true })
-- end, { desc = "Ask ChatGPT with a prompt" })
